### ISSUE TITLE
Mirkats bug

### ISSUE THREAD

**Issue by pllittle** [cran/MiRKAT#2]
Hi,

I've downloaded the 1.1.3 package version and I'm interested in running survival kernel models. I was curious if there was a bug in the MiRKATS() function. I would simply shuffle the order of subjects in the outcome (y), covariates (X), and kernel (Ks) and the function would result in inconsistent p-values. I believe the issue is b/c the ordering of subjects is set based on the "obstime" for objects U, D, and X, but not K.

Thanks!

**Comment by gaborcsardi** [comment]
Hi, this is a read-only mirror of CRAN, please see the package authors and possibly URLs in the `DESCRIPTION` file. Thanks!
